
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
#include "schema.xsd.h"

typedef struct _schema_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct // Grafo
        {
            struct // Ligacao
            {
                WS_FIELD_DESCRIPTION Forca;
                WS_FIELD_DESCRIPTION Peso;
                struct // User
                {
                    WS_FIELD_DESCRIPTION Definido;
                    WS_FIELD_DESCRIPTION Id;
                    WS_FIELD_DESCRIPTION Profile;
                    WS_FIELD_DESCRIPTION Raio;
                    WS_FIELD_DESCRIPTION Tags;
                    WS_FIELD_DESCRIPTION Username;
                    WS_FIELD_DESCRIPTION X;
                    WS_FIELD_DESCRIPTION Y;
                    WS_FIELD_DESCRIPTION Z;
                    WS_FIELD_DESCRIPTION* UserFields [9]; 
                } Userdescs; // end of User
                WS_FIELD_DESCRIPTION User1;
                WS_FIELD_DESCRIPTION User2;
                WS_FIELD_DESCRIPTION* LigacaoFields [4]; 
            } Ligacaodescs; // end of Ligacao
            WS_FIELD_DESCRIPTION Ligacoes;
            WS_FIELD_DESCRIPTION NrArcos;
            WS_FIELD_DESCRIPTION NrNos;
            WS_FIELD_DESCRIPTION Users;
            WS_FIELD_DESCRIPTION* GrafoFields [4]; 
        } Grafodescs; // end of Grafo
        struct // ArrayOfLigacao
        {
            WS_FIELD_DESCRIPTION Ligacao;
            WS_FIELD_DESCRIPTION* ArrayOfLigacaoFields [1]; 
        } ArrayOfLigacaodescs; // end of ArrayOfLigacao
        struct // ArrayOfUser
        {
            WS_FIELD_DESCRIPTION User;
            WS_FIELD_DESCRIPTION* ArrayOfUserFields [1]; 
        } ArrayOfUserdescs; // end of ArrayOfUser
    } globalTypes;  // end of global types
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING GrafoTypeName;  // Grafo
            WS_XML_STRING GrafoTypeNamespace;  // http://schemas.datacontract.org/2004/07/
            WS_XML_STRING LigacaoTypeName;  // Ligacao
            WS_XML_STRING LigacaoForcaLocalName;  // Forca
            WS_XML_STRING LigacaoPesoLocalName;  // Peso
            WS_XML_STRING UserTypeName;  // User
            WS_XML_STRING UserDefinidoLocalName;  // Definido
            WS_XML_STRING UserIdLocalName;  // Id
            WS_XML_STRING UserProfileLocalName;  // string
            WS_XML_STRING UserProfileNamespace;  // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            WS_XML_STRING UserProfileWrapperName;  // Profile
            WS_XML_STRING UserRaioLocalName;  // Raio
            WS_XML_STRING UserTagsWrapperName;  // Tags
            WS_XML_STRING UserUsernameLocalName;  // Username
            WS_XML_STRING UserXLocalName;  // X
            WS_XML_STRING UserYLocalName;  // Y
            WS_XML_STRING UserZLocalName;  // Z
            WS_XML_STRING LigacaoUser1LocalName;  // User1
            WS_XML_STRING LigacaoUser2LocalName;  // User2
            WS_XML_STRING GrafoLigacoesWrapperName;  // Ligacoes
            WS_XML_STRING GrafoNrArcosLocalName;  // NrArcos
            WS_XML_STRING GrafoNrNosLocalName;  // NrNos
            WS_XML_STRING GrafoUsersWrapperName;  // Users
            WS_XML_STRING ArrayOfLigacaoTypeName;  // ArrayOfLigacao
            WS_XML_STRING ArrayOfUserTypeName;  // ArrayOfUser
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _schema_xsdLocalDefinitions;

const static _schema_xsdLocalDefinitions schema_xsdLocalDefinitions =
{
    { // global types
        0,
        {   // Grafo
            {   // Ligacao
                { // field description for Forca
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoForcaLocalName, // Forca
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Ligacao, Forca),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for Forca
                { // field description for Peso
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoPesoLocalName, // Peso
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Ligacao, Peso),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for Peso
                {   // User
                    { // field description for Definido
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserDefinidoLocalName, // Definido
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                    WS_BOOL_TYPE,
                    0,
                    WsOffsetOf(User, Definido),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for Definido
                    { // field description for Id
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserIdLocalName, // Id
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                    WS_INT32_TYPE,
                    0,
                    WsOffsetOf(User, Id),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for Id
                    { // field description for Profile
                    WS_REPEATING_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserProfileWrapperName, // Profile
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                    WS_WSZ_TYPE,
                    0,
                    WsOffsetOf(User, Profile),
                     WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
                    0,
                    WsOffsetOf(User, ProfileCount),
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserProfileLocalName, // string
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserProfileNamespace, // http://schemas.microsoft.com/2003/10/Serialization/Arrays
                    0,
                    },    // end of field description for Profile
                    { // field description for Raio
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserRaioLocalName, // Raio
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                    WS_DOUBLE_TYPE,
                    0,
                    WsOffsetOf(User, Raio),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for Raio
                    { // field description for Tags
                    WS_REPEATING_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserTagsWrapperName, // Tags
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                    WS_WSZ_TYPE,
                    0,
                    WsOffsetOf(User, Tags),
                     WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
                    0,
                    WsOffsetOf(User, TagsCount),
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserProfileLocalName, // string
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserProfileNamespace, // http://schemas.microsoft.com/2003/10/Serialization/Arrays
                    0,
                    },    // end of field description for Tags
                    { // field description for Username
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserUsernameLocalName, // Username
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                    WS_WSZ_TYPE,
                    0,
                    WsOffsetOf(User, Username),
                     WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                    0,
                    0xffffffff
                    },    // end of field description for Username
                    { // field description for X
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserXLocalName, // X
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                    WS_DOUBLE_TYPE,
                    0,
                    WsOffsetOf(User, X),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for X
                    { // field description for Y
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserYLocalName, // Y
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                    WS_DOUBLE_TYPE,
                    0,
                    WsOffsetOf(User, Y),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for Y
                    { // field description for Z
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserZLocalName, // Z
                    (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                    WS_DOUBLE_TYPE,
                    0,
                    WsOffsetOf(User, Z),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for Z
                    {    // fields description for User
                    (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.Definido,
                    (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.Id,
                    (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.Profile,
                    (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.Raio,
                    (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.Tags,
                    (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.Username,
                    (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.X,
                    (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.Y,
                    (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.Z,
                    },
                },    // User
                { // field description for User1
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoUser1LocalName, // User1
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_STRUCT_TYPE,
                (void*)&schema_xsd.globalTypes.User,
                WsOffsetOf(Ligacao, User1),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for User1
                { // field description for User2
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoUser2LocalName, // User2
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_STRUCT_TYPE,
                (void*)&schema_xsd.globalTypes.User,
                WsOffsetOf(Ligacao, User2),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for User2
                {    // fields description for Ligacao
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Forca,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Peso,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.User1,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.User2,
                },
            },    // Ligacao
            { // field description for Ligacoes
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoLigacoesWrapperName, // Ligacoes
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Ligacao,
            WsOffsetOf(Grafo, Ligacoes),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(Grafo, LigacoesCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoTypeName, // Ligacao
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for Ligacoes
            { // field description for NrArcos
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoNrArcosLocalName, // NrArcos
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(Grafo, NrArcos),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for NrArcos
            { // field description for NrNos
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoNrNosLocalName, // NrNos
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(Grafo, NrNos),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for NrNos
            { // field description for Users
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoUsersWrapperName, // Users
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.User,
            WsOffsetOf(Grafo, Users),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(Grafo, UsersCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for Users
            {    // fields description for Grafo
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacoes,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.NrArcos,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.NrNos,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Users,
            },
        },    // Grafo
        {   // ArrayOfLigacao
            { // field description for Ligacao
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Ligacao,
            WsOffsetOf(ArrayOfLigacao, Ligacao),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfLigacao, LigacaoCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoTypeName, // Ligacao
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for Ligacao
            {    // fields description for ArrayOfLigacao
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfLigacaodescs.Ligacao,
            },
        },    // ArrayOfLigacao
        {   // ArrayOfUser
            { // field description for User
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.User,
            WsOffsetOf(ArrayOfUser, User),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfUser, UserCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for User
            {    // fields description for ArrayOfUser
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.User,
            },
        },    // ArrayOfUser
    }, // end of global types
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("Grafo",&schema_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/",&schema_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("Ligacao",&schema_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("Forca",&schema_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("Peso",&schema_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("User",&schema_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("Definido",&schema_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("Id",&schema_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("string",&schema_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.microsoft.com/2003/10/Serialization/Arrays",&schema_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("Profile",&schema_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("Raio",&schema_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("Tags",&schema_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("Username",&schema_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("X",&schema_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("Y",&schema_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("Z",&schema_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("User1",&schema_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("User2",&schema_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("Ligacoes",&schema_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("NrArcos",&schema_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("NrNos",&schema_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("Users",&schema_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfLigacao",&schema_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfUser",&schema_xsdLocalDefinitions.dictionary.dict, 24),
        },  // end of xmlStrings
        
        {   // schema_xsddictionary
        // 5a47665d-d3dc-4198-97a6-14f8a659e045 
        { 0x5a47665d, 0xd3dc, 0x4198, { 0x97, 0xa6, 0x14,0xf8, 0xa6, 0x59, 0xe0, 0x45 } },
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings,
        25,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of schema_xsdLocalDefinitions

const _schema_xsd schema_xsd =
{
    {// globalTypes
        {
        sizeof(Grafo),
        __alignof(Grafo),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.GrafoFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.Grafodescs.GrafoFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeName, // Grafo
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for Grafo
        {
        sizeof(ArrayOfLigacao),
        __alignof(ArrayOfLigacao),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfLigacaodescs.ArrayOfLigacaoFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfLigacaodescs.ArrayOfLigacaoFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfLigacaoTypeName, // ArrayOfLigacao
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for ArrayOfLigacao
        {
        sizeof(Ligacao),
        __alignof(Ligacao),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.LigacaoFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.LigacaoFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoTypeName, // Ligacao
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for Ligacao
        {
        sizeof(User),
        __alignof(User),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.UserFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.Grafodescs.Ligacaodescs.Userdescs.UserFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for User
        {
        sizeof(ArrayOfUser),
        __alignof(ArrayOfUser),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.ArrayOfUserFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.ArrayOfUserFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeName, // ArrayOfUser
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for ArrayOfUser
    }, // globalTypes
    {// globalElements
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeName, // Grafo
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Grafo,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfLigacaoTypeName, // ArrayOfLigacao
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArrayOfLigacao,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoTypeName, // Ligacao
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Ligacao,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.User,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeName, // ArrayOfUser
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.GrafoTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArrayOfUser,
        },
    }, // globalElements
}; // end of _schema_xsd
