
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from a WSDL file, the file may contain up to three 
// sets of C/C++ definitions. The first set consists of function declarations that can be 
// used in calling operations on a running web service from client applications. 
// The second set consists of callback declarations that can be used in the 
// implementation of web services.  
// The third set contains definitions C/C++ structures that are used for serialization of 
// C/C++ types to schema types defined in the WSDL file.
//
// The set of function declarations for web services clients may contain the 
// following declaration: 
//
//    HRESULT WINAPI DefaultBinding_ICalculator_Add(
//       __in WS_SERVICE_PROXY* _serviceProxy,
//       __in int a, 
//       __in int b, 
//       __out int* result, 
//       __in WS_HEAP* _heap,
//       __in_opt WS_CALL_PROPERTY* _callProperties,
//       __in const ULONG _callPropertyCount,
//       __in_opt const WS_ASYNC_CONTEXT*_asyncContext,
//       __in_opt WS_ERROR* _error);
//
// This function can be called from an application code to request ICalculator web 
// service to perform operation Add using two integers a and b as input data.
// Once the web service processes this request and sends the result back,
// the result is returned to the caller of this function in the "result" parameter.
// A WS_SERVICE_PROXY must be created using WsCreateServiceProxy() function
// before this proxy function can be invoked.
//
// The set of callbacks for implementation of web services may contain the following 
// definition of a callback: 
//
//    typedef HRESULT (CALLBACK* DefaultBinding_ICalculator_AddCallback) (
//       __in const WS_OPERATION_CONTEXT* _context,
//       __in int a, 
//       __in int b, 
//       __out int* result, 
//       __in const WS_ASYNC_CONTEXT* _asyncContext,
//       __in WS_ERROR* _error); 
//
//    typedef struct DefaultBinding_ICalculatorFunctionTable 
//    {
//         DefaultBinding_ICalculator_AddCallback DefaultBinding_ICalculator_Add;
//    } DefaultBinding_ICalculatorFunctionTable;
//
// This definition can be used to implement a function that defines the Add operation 
// as a part of an ICalculator web service. Once this callback is implemented and 
// the web service is deployed and running, if a client applications attempts to 
// execute the operation Add, the implementation of this callback is called and 
// it receives two integers a and b as input data and it returns a third integer 
// that is the result of the operation. A WS_SERVICE_ENDPOINT must be filled out, 
// and its contract field set to instance of such a function table.  
// WsCreateServiceHost may then be used to register the endpoint as a service.
// 
// The set with definitions of C/C++ structures may contain a definition of the following 
// structure:
//    typedef struct ContactInfo 
//    {
//			WCHAR*  name;
//			WCHAR*  email;
//			__int64 contactID;
//	  } ContactInfo;
//
// This structure corresponds to the following complex type defined in the WSDL file:
//    <s:complexType name="ContactInfo">
//      <s:sequence>
//        <s:element minOccurs="1" maxOccurs="1" name="name" type="s:string" />
//        <s:element minOccurs="1" maxOccurs="1" name="email" type="s:string" />
//        <s:element minOccurs="1" maxOccurs="1" name="contactID" type="s:long" />
//      </s:sequence>
//    </s:complexType>
//
// For more information about content of this file, please see the documentation for
// Wsutil compiler.
// If Wsutil generates this file from a WSDL file and policy processing is enabled using
// policy switch, the file may contain declaration of functions that can be used 
// for creating a proxy to a web service or an endpoint of a web service. 
// For example, the file may contain declaration of the following function:
//
//    HRESULT DefaultBinding_ICalculator_CreateServiceProxy(
//    __in WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
//    __in_ecount_opt(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
//    __in const ULONG proxyPropertyCount,
//    __deref_out_opt WS_SERVICE_PROXY** proxy,
//    __in_opt WS_ERROR* error);
//
// This function can be called from application code to create a service
// proxy object. A service proxy must be created before any request can be sent 
// to the web service.
//
// Also, the file may contain declaration of the following function :
//
//    HRESULT DefaultBinding_ICalculator_CreateServiceEndpoint(
//    __in WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
//    __in_opt WS_STRING address,
//    __in_opt struct DefaultBinding_ICalculatorFunctionTable* functionTable,
//    __in_opt WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
//    __in_ecount_opt(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
//    __in const ULONG endpointPropertyCount,
//    __in WS_HEAP* heap,
//    __deref_out_opt WS_SERVICE_ENDPOINT** serviceEndpoint,
//    __in_opt WS_ERROR* error);
//
// This function can be used to create a Service Host object, which has to be 
// created before a web services starts receiving requests from its clients.
//
// For more information about content of this file, please see the documentation for
// Wsutil compiler.
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following client functions were generated:

//     BasicHttpBinding_IGraphs4Social_Service_carregaGrafo
//     BasicHttpBinding_IGraphs4Social_Service_carregaGrafoAmigosComum
//     BasicHttpBinding_IGraphs4Social_Service_caminhoMaisCurto

// The following server function tables were generated:

//     struct BasicHttpBinding_IGraphs4Social_ServiceFunctionTable

// the following policy helpers were generated:

//  BasicHttpBinding_IGraphs4Social_Service_CreateServiceProxy;
//  BasicHttpBinding_IGraphs4Social_Service_CreateServiceEndpoint;

// The following header files must be included in this order before this one

// #include <WebServices.h>
// #include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
// #include "schema.xsd.h"
// #include "tempuri.org.xsd.h"

////////////////////////////////////////////////
// Policy helper routines
////////////////////////////////////////////////

//  WS_CHANNEL_PROPERTY_ENCODING = WS_ENCODING_XML_UTF8,
//  WS_CHANNEL_PROPERTY_ADDRESSING_VERSION = WS_ADDRESSING_VERSION_TRANSPORT,
//  WS_ENVELOPE_VERSION = WS_ENVELOPE_VERSION_SOAP_1_1,
// client channel type: WS_CHANNEL_TYPE_REQUEST, service endpoint channel type: WS_CHANNEL_TYPE_REPLY

HRESULT BasicHttpBinding_IGraphs4Social_Service_CreateServiceProxy(
    __in_opt WS_HTTP_BINDING_TEMPLATE* templateValue,
    __in_ecount_opt(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    __in const ULONG proxyPropertyCount,
    __deref_out_opt WS_SERVICE_PROXY** _serviceProxy,
    __in_opt WS_ERROR* error);

struct BasicHttpBinding_IGraphs4Social_ServiceFunctionTable;
HRESULT BasicHttpBinding_IGraphs4Social_Service_CreateServiceEndpoint(
    __in_opt WS_HTTP_BINDING_TEMPLATE* templateValue,
    __in_opt CONST WS_STRING* address,
    __in_opt struct BasicHttpBinding_IGraphs4Social_ServiceFunctionTable* functionTable,
    __in_opt WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    __in_ecount_opt(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    __in const ULONG endpointPropertyCount,
    __in WS_HEAP* heap,
    __deref_out_opt WS_SERVICE_ENDPOINT** serviceEndpoint,
    __in_opt WS_ERROR* error);

////////////////////////////////////////////////
// Client functions definitions
////////////////////////////////////////////////

// operation: BasicHttpBinding_IGraphs4Social_Service_carregaGrafo
HRESULT WINAPI BasicHttpBinding_IGraphs4Social_Service_carregaGrafo(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in_opt __nullterminated WCHAR* username, 
    __deref_out_opt Grafo** carregaGrafoResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error);

// operation: BasicHttpBinding_IGraphs4Social_Service_carregaGrafoAmigosComum
HRESULT WINAPI BasicHttpBinding_IGraphs4Social_Service_carregaGrafoAmigosComum(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in_opt __nullterminated WCHAR* username1, 
    __in_opt __nullterminated WCHAR* username2, 
    __deref_out_opt Grafo** carregaGrafoAmigosComumResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error);

// operation: BasicHttpBinding_IGraphs4Social_Service_caminhoMaisCurto
HRESULT WINAPI BasicHttpBinding_IGraphs4Social_Service_caminhoMaisCurto(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in_opt __nullterminated WCHAR* username1, 
    __in_opt __nullterminated WCHAR* username2, 
    __out_opt __deref __nullterminated WCHAR** caminhoMaisCurtoResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error);

////////////////////////////////////////////////
// Service functions definitions
////////////////////////////////////////////////

typedef HRESULT (CALLBACK* BasicHttpBinding_IGraphs4Social_Service_carregaGrafoCallback) (
    __in const WS_OPERATION_CONTEXT* _context,
    __in_opt __nullterminated WCHAR* username, 
    __deref_out_opt Grafo** carregaGrafoResult, 
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error);

typedef HRESULT (CALLBACK* BasicHttpBinding_IGraphs4Social_Service_carregaGrafoAmigosComumCallback) (
    __in const WS_OPERATION_CONTEXT* _context,
    __in_opt __nullterminated WCHAR* username1, 
    __in_opt __nullterminated WCHAR* username2, 
    __deref_out_opt Grafo** carregaGrafoAmigosComumResult, 
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error);

typedef HRESULT (CALLBACK* BasicHttpBinding_IGraphs4Social_Service_caminhoMaisCurtoCallback) (
    __in const WS_OPERATION_CONTEXT* _context,
    __in_opt __nullterminated WCHAR* username1, 
    __in_opt __nullterminated WCHAR* username2, 
    __out_opt __deref __nullterminated WCHAR** caminhoMaisCurtoResult, 
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error);

// binding: BasicHttpBinding_IGraphs4Social_Service
typedef struct BasicHttpBinding_IGraphs4Social_ServiceFunctionTable 
{
    BasicHttpBinding_IGraphs4Social_Service_carregaGrafoCallback BasicHttpBinding_IGraphs4Social_Service_carregaGrafo;
    BasicHttpBinding_IGraphs4Social_Service_carregaGrafoAmigosComumCallback BasicHttpBinding_IGraphs4Social_Service_carregaGrafoAmigosComum;
    BasicHttpBinding_IGraphs4Social_Service_caminhoMaisCurtoCallback BasicHttpBinding_IGraphs4Social_Service_caminhoMaisCurto;
} BasicHttpBinding_IGraphs4Social_ServiceFunctionTable;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _tempuri_org_wsdl
{
    struct // messages
    {
        // message: IGraphs4Social_Service_carregaGrafo_InputMessage
        // c type: _carregaGrafo
        // action: "http://tempuri.org/IGraphs4Social_Service/carregaGrafo"
        // messageDescription: tempuri_org_wsdl.messages.IGraphs4Social_Service_carregaGrafo_InputMessage
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_carregaGrafo_InputMessage;
        
        // message: IGraphs4Social_Service_carregaGrafo_OutputMessage
        // c type: _carregaGrafoResponse
        // action: "http://tempuri.org/IGraphs4Social_Service/carregaGrafoResponse"
        // messageDescription: tempuri_org_wsdl.messages.IGraphs4Social_Service_carregaGrafo_OutputMessage
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_carregaGrafo_OutputMessage;
        
        // message: IGraphs4Social_Service_carregaGrafoAmigosComum_InputMessage
        // c type: _carregaGrafoAmigosComum
        // action: "http://tempuri.org/IGraphs4Social_Service/carregaGrafoAmigosComum"
        // messageDescription: tempuri_org_wsdl.messages.IGraphs4Social_Service_carregaGrafoAmigosComum_InputMessage
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_carregaGrafoAmigosComum_InputMessage;
        
        // message: IGraphs4Social_Service_carregaGrafoAmigosComum_OutputMessage
        // c type: _carregaGrafoAmigosComumResponse
        // action: "http://tempuri.org/IGraphs4Social_Service/carregaGrafoAmigosComumResponse"
        // messageDescription: tempuri_org_wsdl.messages.IGraphs4Social_Service_carregaGrafoAmigosComum_OutputMessage
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_carregaGrafoAmigosComum_OutputMessage;
        
        // message: IGraphs4Social_Service_caminhoMaisCurto_InputMessage
        // c type: _caminhoMaisCurto
        // action: "http://tempuri.org/IGraphs4Social_Service/caminhoMaisCurto"
        // messageDescription: tempuri_org_wsdl.messages.IGraphs4Social_Service_caminhoMaisCurto_InputMessage
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_caminhoMaisCurto_InputMessage;
        
        // message: IGraphs4Social_Service_caminhoMaisCurto_OutputMessage
        // c type: _caminhoMaisCurtoResponse
        // action: "http://tempuri.org/IGraphs4Social_Service/caminhoMaisCurtoResponse"
        // messageDescription: tempuri_org_wsdl.messages.IGraphs4Social_Service_caminhoMaisCurto_OutputMessage
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_caminhoMaisCurto_OutputMessage;
        
    } messages;
    struct // contracts
    {
        // binding: BasicHttpBinding_IGraphs4Social_Service
        // portType: IGraphs4Social_Service
        // operation: BasicHttpBinding_IGraphs4Social_Service_carregaGrafo
        //     input message: IGraphs4Social_Service_carregaGrafo_InputMessage
        //     output message: IGraphs4Social_Service_carregaGrafo_OutputMessage
        // operation: BasicHttpBinding_IGraphs4Social_Service_carregaGrafoAmigosComum
        //     input message: IGraphs4Social_Service_carregaGrafoAmigosComum_InputMessage
        //     output message: IGraphs4Social_Service_carregaGrafoAmigosComum_OutputMessage
        // operation: BasicHttpBinding_IGraphs4Social_Service_caminhoMaisCurto
        //     input message: IGraphs4Social_Service_caminhoMaisCurto_InputMessage
        //     output message: IGraphs4Social_Service_caminhoMaisCurto_OutputMessage
        // contractDescription: tempuri_org_wsdl.contracts.BasicHttpBinding_IGraphs4Social_Service
        WS_CONTRACT_DESCRIPTION BasicHttpBinding_IGraphs4Social_Service;
        
    } contracts;
    struct // policies
    {
        // policy for binding: BasicHttpBinding_IGraphs4Social_Service
        // port name: BasicHttpBinding_IGraphs4Social_Service, binding: BasicHttpBinding_IGraphs4Social_Service, namespace: http://tempuri.org/
        WS_HTTP_POLICY_DESCRIPTION BasicHttpBinding_IGraphs4Social_Service;
    } policies;
} _tempuri_org_wsdl;

extern const _tempuri_org_wsdl tempuri_org_wsdl;

#ifdef __cplusplus
}
#endif

