//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConsumer.moduloIA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="moduloIA.IModuloIa")]
    public interface IModuloIa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuloIa/tamanhoRede", ReplyAction="http://tempuri.org/IModuloIa/tamanhoRedeResponse")]
        int tamanhoRede(int nivel, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuloIa/tamanhoRede", ReplyAction="http://tempuri.org/IModuloIa/tamanhoRedeResponse")]
        System.Threading.Tasks.Task<int> tamanhoRedeAsync(int nivel, string user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModuloIaChannel : WebConsumer.moduloIA.IModuloIa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModuloIaClient : System.ServiceModel.ClientBase<WebConsumer.moduloIA.IModuloIa>, WebConsumer.moduloIA.IModuloIa {
        
        public ModuloIaClient() {
        }
        
        public ModuloIaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModuloIaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuloIaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuloIaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int tamanhoRede(int nivel, string user) {
            return base.Channel.tamanhoRede(nivel, user);
        }
        
        public System.Threading.Tasks.Task<int> tamanhoRedeAsync(int nivel, string user) {
            return base.Channel.tamanhoRedeAsync(nivel, user);
        }
    }
}
