
#include <WebServices.h>
#include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct Grafo;
//     struct ArrayOfLigacao;
//     struct Ligacao;
//     struct User;
//     struct ArrayOfUser;
//     struct Grafo;
//     struct ArrayOfLigacao;
//     struct Ligacao;
//     struct User;
//     struct ArrayOfUser;

// The following header files must be included in this order before this one

// #include <WebServices.h>
// #include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: schema_xsd.globalTypes.Grafo
typedef struct Grafo 
{
    unsigned int LigacoesCount;
    __field_ecount_opt(LigacoesCount)struct Ligacao** Ligacoes; // optional
    int NrArcos;
    int NrNos;
    unsigned int UsersCount;
    __field_ecount_opt(UsersCount)struct User** Users; // optional
} Grafo;

// typeDescription: schema_xsd.globalTypes.Ligacao
typedef struct Ligacao 
{
    int Forca;
    int Peso;
    WCHAR* Tag; // optional
    struct User* User1; // optional
    struct User* User2; // optional
} Ligacao;

// typeDescription: schema_xsd.globalTypes.User
typedef struct User 
{
    BOOL Definido;
    int Id;
    unsigned int ProfileCount;
    __field_ecount_opt(ProfileCount)WCHAR** Profile; // optional
    double Raio;
    unsigned int TagsCount;
    __field_ecount_opt(TagsCount)WCHAR** Tags; // optional
    WCHAR* Username; // optional
    double X;
    double Y;
    double Z;
} User;

// typeDescription: schema_xsd.globalTypes.ArrayOfLigacao
typedef struct ArrayOfLigacao 
{
    unsigned int LigacaoCount;
    __field_ecount(LigacaoCount)struct Ligacao** Ligacao; // optional
} ArrayOfLigacao;

// typeDescription: schema_xsd.globalTypes.ArrayOfUser
typedef struct ArrayOfUser 
{
    unsigned int UserCount;
    __field_ecount(UserCount)struct User** User; // optional
} ArrayOfUser;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _schema_xsd
{
    struct // globalTypes
    {
        // xml type: Grafo ("http://schemas.datacontract.org/2004/07/")
        // c type: Grafo
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: schema_xsd.globalTypes.Grafo
        WS_STRUCT_DESCRIPTION Grafo;
        
        // xml type: ArrayOfLigacao ("http://schemas.datacontract.org/2004/07/")
        // c type: ArrayOfLigacao
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: schema_xsd.globalTypes.ArrayOfLigacao
        WS_STRUCT_DESCRIPTION ArrayOfLigacao;
        
        // xml type: Ligacao ("http://schemas.datacontract.org/2004/07/")
        // c type: Ligacao
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: schema_xsd.globalTypes.Ligacao
        WS_STRUCT_DESCRIPTION Ligacao;
        
        // xml type: User ("http://schemas.datacontract.org/2004/07/")
        // c type: User
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: schema_xsd.globalTypes.User
        WS_STRUCT_DESCRIPTION User;
        
        // xml type: ArrayOfUser ("http://schemas.datacontract.org/2004/07/")
        // c type: ArrayOfUser
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: schema_xsd.globalTypes.ArrayOfUser
        WS_STRUCT_DESCRIPTION ArrayOfUser;
        
    } globalTypes;
    struct // globalElements
    {
        // xml element: Grafo ("http://schemas.datacontract.org/2004/07/")
        // c type: Grafo
        // elementDescription: schema_xsd.globalElements.Grafo
        WS_ELEMENT_DESCRIPTION Grafo;
        
        // xml element: ArrayOfLigacao ("http://schemas.datacontract.org/2004/07/")
        // c type: ArrayOfLigacao
        // elementDescription: schema_xsd.globalElements.ArrayOfLigacao
        WS_ELEMENT_DESCRIPTION ArrayOfLigacao;
        
        // xml element: Ligacao ("http://schemas.datacontract.org/2004/07/")
        // c type: Ligacao
        // elementDescription: schema_xsd.globalElements.Ligacao
        WS_ELEMENT_DESCRIPTION Ligacao;
        
        // xml element: User ("http://schemas.datacontract.org/2004/07/")
        // c type: User
        // elementDescription: schema_xsd.globalElements.User
        WS_ELEMENT_DESCRIPTION User;
        
        // xml element: ArrayOfUser ("http://schemas.datacontract.org/2004/07/")
        // c type: ArrayOfUser
        // elementDescription: schema_xsd.globalElements.ArrayOfUser
        WS_ELEMENT_DESCRIPTION ArrayOfUser;
        
    } globalElements;
} _schema_xsd;

extern const _schema_xsd schema_xsd;

#ifdef __cplusplus
}
#endif

