
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
#include "schema.xsd.h"
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct // _carregaGrafo
        {
            WS_FIELD_DESCRIPTION username;
            WS_FIELD_DESCRIPTION* _carregaGrafoFields [1]; 
        } _carregaGrafodescs; // end of _carregaGrafo
        struct // _carregaGrafoResponse
        {
            WS_FIELD_DESCRIPTION carregaGrafoResult;
            WS_FIELD_DESCRIPTION* _carregaGrafoResponseFields [1]; 
        } _carregaGrafoResponsedescs; // end of _carregaGrafoResponse
        struct // _carregaGrafoAmigosComum
        {
            WS_FIELD_DESCRIPTION username1;
            WS_FIELD_DESCRIPTION username2;
            WS_FIELD_DESCRIPTION* _carregaGrafoAmigosComumFields [2]; 
        } _carregaGrafoAmigosComumdescs; // end of _carregaGrafoAmigosComum
        struct // _carregaGrafoAmigosComumResponse
        {
            WS_FIELD_DESCRIPTION carregaGrafoAmigosComumResult;
            WS_FIELD_DESCRIPTION* _carregaGrafoAmigosComumResponseFields [1]; 
        } _carregaGrafoAmigosComumResponsedescs; // end of _carregaGrafoAmigosComumResponse
        struct // _caminhoMaisCurto
        {
            WS_FIELD_DESCRIPTION username1;
            WS_FIELD_DESCRIPTION username2;
            WS_FIELD_DESCRIPTION* _caminhoMaisCurtoFields [2]; 
        } _caminhoMaisCurtodescs; // end of _caminhoMaisCurto
        struct // _caminhoMaisCurtoResponse
        {
            WS_FIELD_DESCRIPTION caminhoMaisCurtoResult;
            WS_FIELD_DESCRIPTION* _caminhoMaisCurtoResponseFields [1]; 
        } _caminhoMaisCurtoResponsedescs; // end of _caminhoMaisCurtoResponse
    } globalElements;  // end of global elements
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING _carregaGrafoTypeName;  // carregaGrafo
            WS_XML_STRING _carregaGrafoTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _carregaGrafousernameLocalName;  // username
            WS_XML_STRING _carregaGrafoResponseTypeName;  // carregaGrafoResponse
            WS_XML_STRING _carregaGrafoResponsecarregaGrafoResultLocalName;  // carregaGrafoResult
            WS_XML_STRING _carregaGrafoAmigosComumTypeName;  // carregaGrafoAmigosComum
            WS_XML_STRING _carregaGrafoAmigosComumusername1LocalName;  // username1
            WS_XML_STRING _carregaGrafoAmigosComumusername2LocalName;  // username2
            WS_XML_STRING _carregaGrafoAmigosComumResponseTypeName;  // carregaGrafoAmigosComumResponse
            WS_XML_STRING _carregaGrafoAmigosComumResponsecarregaGrafoAmigosComumResultLocalName;  // carregaGrafoAmigosComumResult
            WS_XML_STRING _caminhoMaisCurtoTypeName;  // caminhoMaisCurto
            WS_XML_STRING _caminhoMaisCurtoResponseTypeName;  // caminhoMaisCurtoResponse
            WS_XML_STRING _caminhoMaisCurtoResponsecaminhoMaisCurtoResultLocalName;  // caminhoMaisCurtoResult
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {   // _carregaGrafo
            { // field description for username
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafousernameLocalName, // username
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_carregaGrafo, username),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for username
            {    // fields description for _carregaGrafo
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafodescs.username,
            },
        },    // _carregaGrafo
        {   // _carregaGrafoResponse
            { // field description for carregaGrafoResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoResponsecarregaGrafoResultLocalName, // carregaGrafoResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Grafo,
            WsOffsetOf(_carregaGrafoResponse, carregaGrafoResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for carregaGrafoResult
            {    // fields description for _carregaGrafoResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoResponsedescs.carregaGrafoResult,
            },
        },    // _carregaGrafoResponse
        {   // _carregaGrafoAmigosComum
            { // field description for username1
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoAmigosComumusername1LocalName, // username1
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_carregaGrafoAmigosComum, username1),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for username1
            { // field description for username2
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoAmigosComumusername2LocalName, // username2
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_carregaGrafoAmigosComum, username2),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for username2
            {    // fields description for _carregaGrafoAmigosComum
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoAmigosComumdescs.username1,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoAmigosComumdescs.username2,
            },
        },    // _carregaGrafoAmigosComum
        {   // _carregaGrafoAmigosComumResponse
            { // field description for carregaGrafoAmigosComumResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoAmigosComumResponsecarregaGrafoAmigosComumResultLocalName, // carregaGrafoAmigosComumResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Grafo,
            WsOffsetOf(_carregaGrafoAmigosComumResponse, carregaGrafoAmigosComumResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for carregaGrafoAmigosComumResult
            {    // fields description for _carregaGrafoAmigosComumResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoAmigosComumResponsedescs.carregaGrafoAmigosComumResult,
            },
        },    // _carregaGrafoAmigosComumResponse
        {   // _caminhoMaisCurto
            { // field description for username1
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoAmigosComumusername1LocalName, // username1
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_caminhoMaisCurto, username1),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for username1
            { // field description for username2
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoAmigosComumusername2LocalName, // username2
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_caminhoMaisCurto, username2),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for username2
            {    // fields description for _caminhoMaisCurto
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._caminhoMaisCurtodescs.username1,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._caminhoMaisCurtodescs.username2,
            },
        },    // _caminhoMaisCurto
        {   // _caminhoMaisCurtoResponse
            { // field description for caminhoMaisCurtoResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._caminhoMaisCurtoResponsecaminhoMaisCurtoResultLocalName, // caminhoMaisCurtoResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_caminhoMaisCurtoResponse, caminhoMaisCurtoResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for caminhoMaisCurtoResult
            {    // fields description for _caminhoMaisCurtoResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._caminhoMaisCurtoResponsedescs.caminhoMaisCurtoResult,
            },
        },    // _caminhoMaisCurtoResponse
    }, // end of global elements
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("carregaGrafo",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("username",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("carregaGrafoResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("carregaGrafoResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("carregaGrafoAmigosComum",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("username1",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("username2",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("carregaGrafoAmigosComumResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("carregaGrafoAmigosComumResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("caminhoMaisCurto",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("caminhoMaisCurtoResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("caminhoMaisCurtoResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 12),
        },  // end of xmlStrings
        
        {   // tempuri_org_xsddictionary
        // e6246224-daa3-492a-983b-36a2ccd033f1 
        { 0xe6246224, 0xdaa3, 0x492a, { 0x98, 0x3b, 0x36,0xa2, 0xcc, 0xd0, 0x33, 0xf1 } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        13,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {// globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeName, // carregaGrafo
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.carregaGrafo,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoResponseTypeName, // carregaGrafoResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.carregaGrafoResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoAmigosComumTypeName, // carregaGrafoAmigosComum
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.carregaGrafoAmigosComum,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoAmigosComumResponseTypeName, // carregaGrafoAmigosComumResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.carregaGrafoAmigosComumResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._caminhoMaisCurtoTypeName, // caminhoMaisCurto
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.caminhoMaisCurto,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._caminhoMaisCurtoResponseTypeName, // caminhoMaisCurtoResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.caminhoMaisCurtoResponse,
        },
    }, // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_carregaGrafo),
        __alignof(_carregaGrafo),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafodescs._carregaGrafoFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafodescs._carregaGrafoFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeName, // carregaGrafo
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _carregaGrafo
        {
        sizeof(_carregaGrafoResponse),
        __alignof(_carregaGrafoResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoResponsedescs._carregaGrafoResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoResponsedescs._carregaGrafoResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoResponseTypeName, // carregaGrafoResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _carregaGrafoResponse
        {
        sizeof(_carregaGrafoAmigosComum),
        __alignof(_carregaGrafoAmigosComum),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoAmigosComumdescs._carregaGrafoAmigosComumFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoAmigosComumdescs._carregaGrafoAmigosComumFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoAmigosComumTypeName, // carregaGrafoAmigosComum
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _carregaGrafoAmigosComum
        {
        sizeof(_carregaGrafoAmigosComumResponse),
        __alignof(_carregaGrafoAmigosComumResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoAmigosComumResponsedescs._carregaGrafoAmigosComumResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoAmigosComumResponsedescs._carregaGrafoAmigosComumResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoAmigosComumResponseTypeName, // carregaGrafoAmigosComumResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _carregaGrafoAmigosComumResponse
        {
        sizeof(_caminhoMaisCurto),
        __alignof(_caminhoMaisCurto),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._caminhoMaisCurtodescs._caminhoMaisCurtoFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._caminhoMaisCurtodescs._caminhoMaisCurtoFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._caminhoMaisCurtoTypeName, // caminhoMaisCurto
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _caminhoMaisCurto
        {
        sizeof(_caminhoMaisCurtoResponse),
        __alignof(_caminhoMaisCurtoResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._caminhoMaisCurtoResponsedescs._caminhoMaisCurtoResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._caminhoMaisCurtoResponsedescs._caminhoMaisCurtoResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._caminhoMaisCurtoResponseTypeName, // caminhoMaisCurtoResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _caminhoMaisCurtoResponse
    }, // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
