
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct // _carregaGrafo
        {
            WS_FIELD_DESCRIPTION username;
            WS_FIELD_DESCRIPTION* _carregaGrafoFields [1]; 
        } _carregaGrafodescs; // end of _carregaGrafo
        struct // _carregaGrafoResponse
        {
            WS_FIELD_DESCRIPTION carregaGrafoResult;
            WS_FIELD_DESCRIPTION* _carregaGrafoResponseFields [1]; 
        } _carregaGrafoResponsedescs; // end of _carregaGrafoResponse
    } globalElements;  // end of global elements
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING _carregaGrafoTypeName;  // carregaGrafo
            WS_XML_STRING _carregaGrafoTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _carregaGrafousernameLocalName;  // username
            WS_XML_STRING _carregaGrafoResponseTypeName;  // carregaGrafoResponse
            WS_XML_STRING _carregaGrafoResponsecarregaGrafoResultLocalName;  // carregaGrafoResult
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {   // _carregaGrafo
            { // field description for username
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafousernameLocalName, // username
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_carregaGrafo, username),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for username
            {    // fields description for _carregaGrafo
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafodescs.username,
            },
        },    // _carregaGrafo
        {   // _carregaGrafoResponse
            { // field description for carregaGrafoResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoResponsecarregaGrafoResultLocalName, // carregaGrafoResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_carregaGrafoResponse, carregaGrafoResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for carregaGrafoResult
            {    // fields description for _carregaGrafoResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoResponsedescs.carregaGrafoResult,
            },
        },    // _carregaGrafoResponse
    }, // end of global elements
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("carregaGrafo",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("username",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("carregaGrafoResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("carregaGrafoResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
        },  // end of xmlStrings
        
        {   // tempuri_org_xsddictionary
        // 8d44e0af-808c-4db3-a784-0fdda7cb3591 
        { 0x8d44e0af, 0x808c, 0x4db3, { 0xa7, 0x84, 0x0f,0xdd, 0xa7, 0xcb, 0x35, 0x91 } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        5,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {// globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeName, // carregaGrafo
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.carregaGrafo,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoResponseTypeName, // carregaGrafoResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.carregaGrafoResponse,
        },
    }, // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_carregaGrafo),
        __alignof(_carregaGrafo),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafodescs._carregaGrafoFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafodescs._carregaGrafoFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeName, // carregaGrafo
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _carregaGrafo
        {
        sizeof(_carregaGrafoResponse),
        __alignof(_carregaGrafoResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoResponsedescs._carregaGrafoResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._carregaGrafoResponsedescs._carregaGrafoResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoResponseTypeName, // carregaGrafoResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._carregaGrafoTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _carregaGrafoResponse
    }, // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
