
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct _carregaGrafo;
//     struct _carregaGrafoResponse;
//     struct _carregaGrafoAmigosComum;
//     struct _carregaGrafoAmigosComumResponse;
//     struct _caminhoMaisCurto;
//     struct _caminhoMaisCurtoResponse;
//     struct _verificarUser;
//     struct _verificarUserResponse;

// The following header files must be included in this order before this one

// #include <WebServices.h>
// #include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
// #include "schema.xsd.h"

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: n/a
typedef struct _carregaGrafo 
{
    WCHAR* username; // optional
} _carregaGrafo;

// typeDescription: n/a
typedef struct _carregaGrafoResponse 
{
    struct Grafo* carregaGrafoResult; // optional
} _carregaGrafoResponse;

// typeDescription: n/a
typedef struct _carregaGrafoAmigosComum 
{
    WCHAR* username1; // optional
    WCHAR* username2; // optional
} _carregaGrafoAmigosComum;

// typeDescription: n/a
typedef struct _carregaGrafoAmigosComumResponse 
{
    struct Grafo* carregaGrafoAmigosComumResult; // optional
} _carregaGrafoAmigosComumResponse;

// typeDescription: n/a
typedef struct _caminhoMaisCurto 
{
    WCHAR* username1; // optional
    WCHAR* username2; // optional
} _caminhoMaisCurto;

// typeDescription: n/a
typedef struct _caminhoMaisCurtoResponse 
{
    WCHAR* caminhoMaisCurtoResult; // optional
} _caminhoMaisCurtoResponse;

// typeDescription: n/a
typedef struct _verificarUser 
{
    WCHAR* username; // optional
} _verificarUser;

// typeDescription: n/a
typedef struct _verificarUserResponse 
{
    BOOL verificarUserResult;
} _verificarUserResponse;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _tempuri_org_xsd
{
    struct // globalElements
    {
        // xml element: carregaGrafo ("http://tempuri.org/")
        // c type: _carregaGrafo
        // elementDescription: tempuri_org_xsd.globalElements.carregaGrafo
        WS_ELEMENT_DESCRIPTION carregaGrafo;
        
        // xml element: carregaGrafoResponse ("http://tempuri.org/")
        // c type: _carregaGrafoResponse
        // elementDescription: tempuri_org_xsd.globalElements.carregaGrafoResponse
        WS_ELEMENT_DESCRIPTION carregaGrafoResponse;
        
        // xml element: carregaGrafoAmigosComum ("http://tempuri.org/")
        // c type: _carregaGrafoAmigosComum
        // elementDescription: tempuri_org_xsd.globalElements.carregaGrafoAmigosComum
        WS_ELEMENT_DESCRIPTION carregaGrafoAmigosComum;
        
        // xml element: carregaGrafoAmigosComumResponse ("http://tempuri.org/")
        // c type: _carregaGrafoAmigosComumResponse
        // elementDescription: tempuri_org_xsd.globalElements.carregaGrafoAmigosComumResponse
        WS_ELEMENT_DESCRIPTION carregaGrafoAmigosComumResponse;
        
        // xml element: caminhoMaisCurto ("http://tempuri.org/")
        // c type: _caminhoMaisCurto
        // elementDescription: tempuri_org_xsd.globalElements.caminhoMaisCurto
        WS_ELEMENT_DESCRIPTION caminhoMaisCurto;
        
        // xml element: caminhoMaisCurtoResponse ("http://tempuri.org/")
        // c type: _caminhoMaisCurtoResponse
        // elementDescription: tempuri_org_xsd.globalElements.caminhoMaisCurtoResponse
        WS_ELEMENT_DESCRIPTION caminhoMaisCurtoResponse;
        
        // xml element: verificarUser ("http://tempuri.org/")
        // c type: _verificarUser
        // elementDescription: tempuri_org_xsd.globalElements.verificarUser
        WS_ELEMENT_DESCRIPTION verificarUser;
        
        // xml element: verificarUserResponse ("http://tempuri.org/")
        // c type: _verificarUserResponse
        // elementDescription: tempuri_org_xsd.globalElements.verificarUserResponse
        WS_ELEMENT_DESCRIPTION verificarUserResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION carregaGrafo;
        WS_STRUCT_DESCRIPTION carregaGrafoResponse;
        WS_STRUCT_DESCRIPTION carregaGrafoAmigosComum;
        WS_STRUCT_DESCRIPTION carregaGrafoAmigosComumResponse;
        WS_STRUCT_DESCRIPTION caminhoMaisCurto;
        WS_STRUCT_DESCRIPTION caminhoMaisCurtoResponse;
        WS_STRUCT_DESCRIPTION verificarUser;
        WS_STRUCT_DESCRIPTION verificarUserResponse;
    } externallyReferencedTypes;
} _tempuri_org_xsd;

extern const _tempuri_org_xsd tempuri_org_xsd;

#ifdef __cplusplus
}
#endif

