
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schema.xsd.h"

typedef struct _schema_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct // Pessoa
        {
            WS_FIELD_DESCRIPTION Idade;
            WS_FIELD_DESCRIPTION Nome;
            WS_FIELD_DESCRIPTION* PessoaFields [2]; 
        } Pessoadescs; // end of Pessoa
        struct // Musica
        {
            WS_FIELD_DESCRIPTION Artist;
            WS_FIELD_DESCRIPTION Title;
            WS_FIELD_DESCRIPTION* MusicaFields [2]; 
        } Musicadescs; // end of Musica
        struct // ArrayOfMusica
        {
            WS_FIELD_DESCRIPTION Musica;
            WS_FIELD_DESCRIPTION* ArrayOfMusicaFields [1]; 
        } ArrayOfMusicadescs; // end of ArrayOfMusica
    } globalTypes;  // end of global types
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING PessoaTypeName;  // Pessoa
            WS_XML_STRING PessoaTypeNamespace;  // http://schemas.datacontract.org/2004/07/
            WS_XML_STRING PessoaIdadeLocalName;  // Idade
            WS_XML_STRING PessoaNomeLocalName;  // Nome
            WS_XML_STRING MusicaTypeName;  // Musica
            WS_XML_STRING MusicaArtistLocalName;  // Artist
            WS_XML_STRING MusicaTitleLocalName;  // Title
            WS_XML_STRING ArrayOfMusicaTypeName;  // ArrayOfMusica
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _schema_xsdLocalDefinitions;

const static _schema_xsdLocalDefinitions schema_xsdLocalDefinitions =
{
    { // global types
        0,
        {   // Pessoa
            { // field description for Idade
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaIdadeLocalName, // Idade
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(Pessoa, Idade),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for Idade
            { // field description for Nome
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaNomeLocalName, // Nome
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Pessoa, Nome),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for Nome
            {    // fields description for Pessoa
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Pessoadescs.Idade,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Pessoadescs.Nome,
            },
        },    // Pessoa
        {   // Musica
            { // field description for Artist
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.MusicaArtistLocalName, // Artist
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Musica, Artist),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for Artist
            { // field description for Title
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.MusicaTitleLocalName, // Title
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Musica, Title),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for Title
            {    // fields description for Musica
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Musicadescs.Artist,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Musicadescs.Title,
            },
        },    // Musica
        {   // ArrayOfMusica
            { // field description for Musica
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Musica,
            WsOffsetOf(ArrayOfMusica, Musica),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfMusica, MusicaCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.MusicaTypeName, // Musica
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for Musica
            {    // fields description for ArrayOfMusica
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfMusicadescs.Musica,
            },
        },    // ArrayOfMusica
    }, // end of global types
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("Pessoa",&schema_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/",&schema_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("Idade",&schema_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("Nome",&schema_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("Musica",&schema_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("Artist",&schema_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("Title",&schema_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfMusica",&schema_xsdLocalDefinitions.dictionary.dict, 7),
        },  // end of xmlStrings
        
        {   // schema_xsddictionary
        // 9f85b14a-87ea-4884-891e-366f3230a05d 
        { 0x9f85b14a, 0x87ea, 0x4884, { 0x89, 0x1e, 0x36,0x6f, 0x32, 0x30, 0xa0, 0x5d } },
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings,
        8,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of schema_xsdLocalDefinitions

const _schema_xsd schema_xsd =
{
    {// globalTypes
        {
        sizeof(Pessoa),
        __alignof(Pessoa),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.Pessoadescs.PessoaFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.Pessoadescs.PessoaFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeName, // Pessoa
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for Pessoa
        {
        sizeof(Musica),
        __alignof(Musica),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.Musicadescs.MusicaFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.Musicadescs.MusicaFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.MusicaTypeName, // Musica
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for Musica
        {
        sizeof(ArrayOfMusica),
        __alignof(ArrayOfMusica),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfMusicadescs.ArrayOfMusicaFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfMusicadescs.ArrayOfMusicaFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfMusicaTypeName, // ArrayOfMusica
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for ArrayOfMusica
    }, // globalTypes
    {// globalElements
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeName, // Pessoa
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Pessoa,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.MusicaTypeName, // Musica
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Musica,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfMusicaTypeName, // ArrayOfMusica
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.PessoaTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArrayOfMusica,
        },
    }, // globalElements
}; // end of _schema_xsd
