
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct Pessoa;
//     struct Musica;
//     struct ArrayOfMusica;
//     struct Pessoa;
//     struct Musica;
//     struct ArrayOfMusica;

// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: schema_xsd.globalTypes.Pessoa
typedef struct Pessoa 
{
    int Idade;
    WCHAR* Nome; // optional
} Pessoa;

// typeDescription: schema_xsd.globalTypes.Musica
typedef struct Musica 
{
    WCHAR* Artist; // optional
    WCHAR* Title; // optional
} Musica;

// typeDescription: schema_xsd.globalTypes.ArrayOfMusica
typedef struct ArrayOfMusica 
{
    unsigned int MusicaCount;
    __field_ecount(MusicaCount)struct Musica** Musica; // optional
} ArrayOfMusica;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _schema_xsd
{
    struct // globalTypes
    {
        // xml type: Pessoa ("http://schemas.datacontract.org/2004/07/")
        // c type: Pessoa
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: schema_xsd.globalTypes.Pessoa
        WS_STRUCT_DESCRIPTION Pessoa;
        
        // xml type: Musica ("http://schemas.datacontract.org/2004/07/")
        // c type: Musica
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: schema_xsd.globalTypes.Musica
        WS_STRUCT_DESCRIPTION Musica;
        
        // xml type: ArrayOfMusica ("http://schemas.datacontract.org/2004/07/")
        // c type: ArrayOfMusica
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: schema_xsd.globalTypes.ArrayOfMusica
        WS_STRUCT_DESCRIPTION ArrayOfMusica;
        
    } globalTypes;
    struct // globalElements
    {
        // xml element: Pessoa ("http://schemas.datacontract.org/2004/07/")
        // c type: Pessoa
        // elementDescription: schema_xsd.globalElements.Pessoa
        WS_ELEMENT_DESCRIPTION Pessoa;
        
        // xml element: Musica ("http://schemas.datacontract.org/2004/07/")
        // c type: Musica
        // elementDescription: schema_xsd.globalElements.Musica
        WS_ELEMENT_DESCRIPTION Musica;
        
        // xml element: ArrayOfMusica ("http://schemas.datacontract.org/2004/07/")
        // c type: ArrayOfMusica
        // elementDescription: schema_xsd.globalElements.ArrayOfMusica
        WS_ELEMENT_DESCRIPTION ArrayOfMusica;
        
    } globalElements;
} _schema_xsd;

extern const _schema_xsd schema_xsd;

#ifdef __cplusplus
}
#endif

