
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schema.xsd.h"
#include "tempuri.org.xsd.h"
#include "tempuri.org.wsdl.h"

typedef struct _tempuri_org_wsdlLocalDefinitions 
{
    struct // messages
    {
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_DoWork_InputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_DoWork_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_Add_InputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_Add_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_getPessoa_InputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_getPessoa_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_getMusica_InputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_getMusica_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_getMusicas_InputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_getMusicas_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_findIdMusica_InputMessage;
        WS_MESSAGE_DESCRIPTION IGraphs4Social_Service_findIdMusica_OutputMessage;
    } messages; // end of messages
    struct // contracts
    {
        struct // BasicHttpBinding_IGraphs4Social_Service
        {
            struct // BasicHttpBinding_IGraphs4Social_Service_DoWork
            {
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGraphs4Social_Service_DoWork;
            } BasicHttpBinding_IGraphs4Social_Service_DoWork;
            struct // BasicHttpBinding_IGraphs4Social_Service_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGraphs4Social_Service_Add;
            } BasicHttpBinding_IGraphs4Social_Service_Add;
            struct // BasicHttpBinding_IGraphs4Social_Service_getPessoa
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGraphs4Social_Service_getPessoa;
            } BasicHttpBinding_IGraphs4Social_Service_getPessoa;
            struct // BasicHttpBinding_IGraphs4Social_Service_getMusica
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGraphs4Social_Service_getMusica;
            } BasicHttpBinding_IGraphs4Social_Service_getMusica;
            struct // BasicHttpBinding_IGraphs4Social_Service_getMusicas
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGraphs4Social_Service_getMusicas;
            } BasicHttpBinding_IGraphs4Social_Service_getMusicas;
            struct // BasicHttpBinding_IGraphs4Social_Service_findIdMusica
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGraphs4Social_Service_findIdMusica;
            } BasicHttpBinding_IGraphs4Social_Service_findIdMusica;
            WS_OPERATION_DESCRIPTION* operations[6];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } BasicHttpBinding_IGraphs4Social_Service;
    } contracts;  // endof contracts 
    struct // policies
    {
        struct // BasicHttpBinding_IGraphs4Social_Service
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } BasicHttpBinding_IGraphs4Social_Service;
    } policies;
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING IGraphs4Social_Service_DoWork_InputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/DoWork
            WS_XML_STRING IGraphs4Social_Service_DoWork_OutputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/DoWorkResponse
            WS_XML_STRING IGraphs4Social_Service_Add_InputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/Add
            WS_XML_STRING IGraphs4Social_Service_Add_OutputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/AddResponse
            WS_XML_STRING IGraphs4Social_Service_getPessoa_InputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/getPessoa
            WS_XML_STRING IGraphs4Social_Service_getPessoa_OutputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/getPessoaResponse
            WS_XML_STRING IGraphs4Social_Service_getMusica_InputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/getMusica
            WS_XML_STRING IGraphs4Social_Service_getMusica_OutputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/getMusicaResponse
            WS_XML_STRING IGraphs4Social_Service_getMusicas_InputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/getMusicas
            WS_XML_STRING IGraphs4Social_Service_getMusicas_OutputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/getMusicasResponse
            WS_XML_STRING IGraphs4Social_Service_findIdMusica_InputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/findIdMusica
            WS_XML_STRING IGraphs4Social_Service_findIdMusica_OutputMessageactionName;  // http://tempuri.org/IGraphs4Social_Service/findIdMusicaResponse
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_wsdlLocalDefinitions;


#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGraphs4Social_Service_DoWorkOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    BasicHttpBinding_IGraphs4Social_Service_DoWorkCallback _operation = (BasicHttpBinding_IGraphs4Social_Service_DoWorkCallback)_callback;
    _stackStruct;
    return _operation( 
        _context,
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGraphs4Social_Service_AddParamStruct 
{
    int* x;
    int* y;
    int* AddResult;
} BasicHttpBinding_IGraphs4Social_Service_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGraphs4Social_Service_AddOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    BasicHttpBinding_IGraphs4Social_Service_AddCallback _operation = (BasicHttpBinding_IGraphs4Social_Service_AddCallback)_callback;
    BasicHttpBinding_IGraphs4Social_Service_AddParamStruct *_stack =(BasicHttpBinding_IGraphs4Social_Service_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->x),
        *(_stack->y),
        (_stack->AddResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGraphs4Social_Service_getPessoaParamStruct 
{
    int* id;
    Pessoa** getPessoaResult;
} BasicHttpBinding_IGraphs4Social_Service_getPessoaParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGraphs4Social_Service_getPessoaOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    BasicHttpBinding_IGraphs4Social_Service_getPessoaCallback _operation = (BasicHttpBinding_IGraphs4Social_Service_getPessoaCallback)_callback;
    BasicHttpBinding_IGraphs4Social_Service_getPessoaParamStruct *_stack =(BasicHttpBinding_IGraphs4Social_Service_getPessoaParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id),
        (_stack->getPessoaResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGraphs4Social_Service_getMusicaParamStruct 
{
    int* id;
    Musica** getMusicaResult;
} BasicHttpBinding_IGraphs4Social_Service_getMusicaParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGraphs4Social_Service_getMusicaOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    BasicHttpBinding_IGraphs4Social_Service_getMusicaCallback _operation = (BasicHttpBinding_IGraphs4Social_Service_getMusicaCallback)_callback;
    BasicHttpBinding_IGraphs4Social_Service_getMusicaParamStruct *_stack =(BasicHttpBinding_IGraphs4Social_Service_getMusicaParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id),
        (_stack->getMusicaResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGraphs4Social_Service_getMusicasParamStruct 
{
    unsigned int* getMusicasResultCount;
    Musica*** getMusicasResult;
} BasicHttpBinding_IGraphs4Social_Service_getMusicasParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGraphs4Social_Service_getMusicasOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    BasicHttpBinding_IGraphs4Social_Service_getMusicasCallback _operation = (BasicHttpBinding_IGraphs4Social_Service_getMusicasCallback)_callback;
    BasicHttpBinding_IGraphs4Social_Service_getMusicasParamStruct *_stack =(BasicHttpBinding_IGraphs4Social_Service_getMusicasParamStruct*)_stackStruct;
    return _operation( 
        _context,
        _stack->getMusicasResultCount,
        (_stack->getMusicasResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGraphs4Social_Service_findIdMusicaParamStruct 
{
    Musica** musica;
    int* findIdMusicaResult;
} BasicHttpBinding_IGraphs4Social_Service_findIdMusicaParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGraphs4Social_Service_findIdMusicaOperationStub(
    __in const WS_OPERATION_CONTEXT* _context,
    __in void* _stackStruct,
    __in const void* _callback,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    BasicHttpBinding_IGraphs4Social_Service_findIdMusicaCallback _operation = (BasicHttpBinding_IGraphs4Social_Service_findIdMusicaCallback)_callback;
    BasicHttpBinding_IGraphs4Social_Service_findIdMusicaParamStruct *_stack =(BasicHttpBinding_IGraphs4Social_Service_findIdMusicaParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->musica),
        (_stack->findIdMusicaResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _tempuri_org_wsdlLocalDefinitions tempuri_org_wsdlLocalDefinitions =
{
    { // messages
        {    // message description for IGraphs4Social_Service_DoWork_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_DoWork_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/DoWork
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DoWork, 
        },    // message description for IGraphs4Social_Service_DoWork_InputMessage
        {    // message description for IGraphs4Social_Service_DoWork_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_DoWork_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/DoWorkResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DoWorkResponse, 
        },    // message description for IGraphs4Social_Service_DoWork_OutputMessage
        {    // message description for IGraphs4Social_Service_Add_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_Add_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/Add
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.Add, 
        },    // message description for IGraphs4Social_Service_Add_InputMessage
        {    // message description for IGraphs4Social_Service_Add_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_Add_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/AddResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.AddResponse, 
        },    // message description for IGraphs4Social_Service_Add_OutputMessage
        {    // message description for IGraphs4Social_Service_getPessoa_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getPessoa_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getPessoa
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getPessoa, 
        },    // message description for IGraphs4Social_Service_getPessoa_InputMessage
        {    // message description for IGraphs4Social_Service_getPessoa_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getPessoa_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getPessoaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getPessoaResponse, 
        },    // message description for IGraphs4Social_Service_getPessoa_OutputMessage
        {    // message description for IGraphs4Social_Service_getMusica_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getMusica_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getMusica
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getMusica, 
        },    // message description for IGraphs4Social_Service_getMusica_InputMessage
        {    // message description for IGraphs4Social_Service_getMusica_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getMusica_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getMusicaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getMusicaResponse, 
        },    // message description for IGraphs4Social_Service_getMusica_OutputMessage
        {    // message description for IGraphs4Social_Service_getMusicas_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getMusicas_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getMusicas
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getMusicas, 
        },    // message description for IGraphs4Social_Service_getMusicas_InputMessage
        {    // message description for IGraphs4Social_Service_getMusicas_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getMusicas_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getMusicasResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getMusicasResponse, 
        },    // message description for IGraphs4Social_Service_getMusicas_OutputMessage
        {    // message description for IGraphs4Social_Service_findIdMusica_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_findIdMusica_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/findIdMusica
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.findIdMusica, 
        },    // message description for IGraphs4Social_Service_findIdMusica_InputMessage
        {    // message description for IGraphs4Social_Service_findIdMusica_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_findIdMusica_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/findIdMusicaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.findIdMusicaResponse, 
        },    // message description for IGraphs4Social_Service_findIdMusica_OutputMessage
    }, // end of messages 
    { // contracts
        {    // BasicHttpBinding_IGraphs4Social_Service,
            { // BasicHttpBinding_IGraphs4Social_Service_DoWork
                {    // operation description for BasicHttpBinding_IGraphs4Social_Service_DoWork
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_DoWork_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_DoWork_OutputMessage, 
                    0,
                    0,
                    0,
                    0,
                    BasicHttpBinding_IGraphs4Social_Service_DoWorkOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGraphs4Social_Service_DoWork
            },  // BasicHttpBinding_IGraphs4Social_Service_DoWork
            { // BasicHttpBinding_IGraphs4Social_Service_Add
                { // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_Add
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1 },
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1 },
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0 },
                },    // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_Add
                {    // operation description for BasicHttpBinding_IGraphs4Social_Service_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_Add_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_Add_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_Add.params,
                    BasicHttpBinding_IGraphs4Social_Service_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGraphs4Social_Service_Add
            },  // BasicHttpBinding_IGraphs4Social_Service_Add
            { // BasicHttpBinding_IGraphs4Social_Service_getPessoa
                { // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_getPessoa
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1 },
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0 },
                },    // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_getPessoa
                {    // operation description for BasicHttpBinding_IGraphs4Social_Service_getPessoa
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_getPessoa_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_getPessoa_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_getPessoa.params,
                    BasicHttpBinding_IGraphs4Social_Service_getPessoaOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGraphs4Social_Service_getPessoa
            },  // BasicHttpBinding_IGraphs4Social_Service_getPessoa
            { // BasicHttpBinding_IGraphs4Social_Service_getMusica
                { // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_getMusica
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1 },
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0 },
                },    // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_getMusica
                {    // operation description for BasicHttpBinding_IGraphs4Social_Service_getMusica
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_getMusica_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_getMusica_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_getMusica.params,
                    BasicHttpBinding_IGraphs4Social_Service_getMusicaOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGraphs4Social_Service_getMusica
            },  // BasicHttpBinding_IGraphs4Social_Service_getMusica
            { // BasicHttpBinding_IGraphs4Social_Service_getMusicas
                { // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_getMusicas
                    { WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0 },
                    { WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0 },
                },    // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_getMusicas
                {    // operation description for BasicHttpBinding_IGraphs4Social_Service_getMusicas
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_getMusicas_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_getMusicas_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_getMusicas.params,
                    BasicHttpBinding_IGraphs4Social_Service_getMusicasOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGraphs4Social_Service_getMusicas
            },  // BasicHttpBinding_IGraphs4Social_Service_getMusicas
            { // BasicHttpBinding_IGraphs4Social_Service_findIdMusica
                { // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_findIdMusica
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1 },
                    { WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0 },
                },    // parameter descriptions for BasicHttpBinding_IGraphs4Social_Service_findIdMusica
                {    // operation description for BasicHttpBinding_IGraphs4Social_Service_findIdMusica
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_findIdMusica_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGraphs4Social_Service_findIdMusica_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_findIdMusica.params,
                    BasicHttpBinding_IGraphs4Social_Service_findIdMusicaOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGraphs4Social_Service_findIdMusica
            },  // BasicHttpBinding_IGraphs4Social_Service_findIdMusica
            {    // array of operations for BasicHttpBinding_IGraphs4Social_Service
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_DoWork.BasicHttpBinding_IGraphs4Social_Service_DoWork,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_Add.BasicHttpBinding_IGraphs4Social_Service_Add,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_getPessoa.BasicHttpBinding_IGraphs4Social_Service_getPessoa,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_getMusica.BasicHttpBinding_IGraphs4Social_Service_getMusica,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_getMusicas.BasicHttpBinding_IGraphs4Social_Service_getMusicas,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_findIdMusica.BasicHttpBinding_IGraphs4Social_Service_findIdMusica,
            },    // array of operations for BasicHttpBinding_IGraphs4Social_Service
            {    // contract description for BasicHttpBinding_IGraphs4Social_Service
            6,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.operations,
            },  // end of contract description for BasicHttpBinding_IGraphs4Social_Service
        },    // BasicHttpBinding_IGraphs4Social_Service
    }, //  end of contracts 
    {// policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGraphs4Social_Service.encoding,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGraphs4Social_Service.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGraphs4Social_Service.addressingVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGraphs4Social_Service.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGraphs4Social_Service.envelopeVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGraphs4Social_Service.envelopeVersion),
                },
            },
        },   // end of BasicHttpBinding_IGraphs4Social_Service,
    }, // policies
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/DoWork",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/DoWorkResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/Add",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/AddResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/getPessoa",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/getPessoaResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/getMusica",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/getMusicaResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/getMusicas",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/getMusicasResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/findIdMusica",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGraphs4Social_Service/findIdMusicaResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 11),
        },  // end of xmlStrings
        
        {   // tempuri_org_wsdldictionary
        // aeeec186-0a8f-4659-beef-9d2d35ed96f1 
        { 0xaeeec186, 0x0a8f, 0x4659, { 0xbe, 0xef, 0x9d,0x2d, 0x35, 0xed, 0x96, 0xf1 } },
        (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings,
        12,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_wsdlLocalDefinitions


// operation: BasicHttpBinding_IGraphs4Social_Service_DoWork
HRESULT WINAPI BasicHttpBinding_IGraphs4Social_Service_DoWork(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_DoWork.BasicHttpBinding_IGraphs4Social_Service_DoWork,
        0,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGraphs4Social_Service_Add
HRESULT WINAPI BasicHttpBinding_IGraphs4Social_Service_Add(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in int x, 
    __in int y, 
    __out int* AddResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &x;
    _argList[1] = &y;
    _argList[2] = &AddResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_Add.BasicHttpBinding_IGraphs4Social_Service_Add,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGraphs4Social_Service_getPessoa
HRESULT WINAPI BasicHttpBinding_IGraphs4Social_Service_getPessoa(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in int id, 
    __deref_out_opt Pessoa** getPessoaResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &id;
    _argList[1] = &getPessoaResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_getPessoa.BasicHttpBinding_IGraphs4Social_Service_getPessoa,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGraphs4Social_Service_getMusica
HRESULT WINAPI BasicHttpBinding_IGraphs4Social_Service_getMusica(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in int id, 
    __deref_out_opt Musica** getMusicaResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &id;
    _argList[1] = &getMusicaResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_getMusica.BasicHttpBinding_IGraphs4Social_Service_getMusica,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGraphs4Social_Service_getMusicas
HRESULT WINAPI BasicHttpBinding_IGraphs4Social_Service_getMusicas(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __out unsigned int* getMusicasResultCount, 
    __deref_out_ecount_opt(*getMusicasResultCount) Musica*** getMusicasResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &getMusicasResultCount;
    _argList[1] = &getMusicasResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_getMusicas.BasicHttpBinding_IGraphs4Social_Service_getMusicas,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGraphs4Social_Service_findIdMusica
HRESULT WINAPI BasicHttpBinding_IGraphs4Social_Service_findIdMusica(
    __in WS_SERVICE_PROXY* _serviceProxy,
    __in_opt Musica* musica, 
    __out int* findIdMusicaResult, 
    __in WS_HEAP* _heap,
    __in_ecount_opt(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    __in const ULONG _callPropertyCount,
    __in_opt const WS_ASYNC_CONTEXT* _asyncContext,
    __in_opt WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &musica;
    _argList[1] = &findIdMusicaResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.BasicHttpBinding_IGraphs4Social_Service_findIdMusica.BasicHttpBinding_IGraphs4Social_Service_findIdMusica,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
const _tempuri_org_wsdl tempuri_org_wsdl =
{
    {// messages
        {    // message description for IGraphs4Social_Service_DoWork_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_DoWork_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/DoWork
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DoWork, 
        },    // message description for IGraphs4Social_Service_DoWork_InputMessage
        {    // message description for IGraphs4Social_Service_DoWork_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_DoWork_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/DoWorkResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DoWorkResponse, 
        },    // message description for IGraphs4Social_Service_DoWork_OutputMessage
        {    // message description for IGraphs4Social_Service_Add_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_Add_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/Add
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.Add, 
        },    // message description for IGraphs4Social_Service_Add_InputMessage
        {    // message description for IGraphs4Social_Service_Add_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_Add_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/AddResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.AddResponse, 
        },    // message description for IGraphs4Social_Service_Add_OutputMessage
        {    // message description for IGraphs4Social_Service_getPessoa_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getPessoa_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getPessoa
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getPessoa, 
        },    // message description for IGraphs4Social_Service_getPessoa_InputMessage
        {    // message description for IGraphs4Social_Service_getPessoa_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getPessoa_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getPessoaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getPessoaResponse, 
        },    // message description for IGraphs4Social_Service_getPessoa_OutputMessage
        {    // message description for IGraphs4Social_Service_getMusica_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getMusica_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getMusica
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getMusica, 
        },    // message description for IGraphs4Social_Service_getMusica_InputMessage
        {    // message description for IGraphs4Social_Service_getMusica_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getMusica_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getMusicaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getMusicaResponse, 
        },    // message description for IGraphs4Social_Service_getMusica_OutputMessage
        {    // message description for IGraphs4Social_Service_getMusicas_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getMusicas_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getMusicas
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getMusicas, 
        },    // message description for IGraphs4Social_Service_getMusicas_InputMessage
        {    // message description for IGraphs4Social_Service_getMusicas_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_getMusicas_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/getMusicasResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getMusicasResponse, 
        },    // message description for IGraphs4Social_Service_getMusicas_OutputMessage
        {    // message description for IGraphs4Social_Service_findIdMusica_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_findIdMusica_InputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/findIdMusica
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.findIdMusica, 
        },    // message description for IGraphs4Social_Service_findIdMusica_InputMessage
        {    // message description for IGraphs4Social_Service_findIdMusica_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGraphs4Social_Service_findIdMusica_OutputMessageactionName, // http://tempuri.org/IGraphs4Social_Service/findIdMusicaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.findIdMusicaResponse, 
        },    // message description for IGraphs4Social_Service_findIdMusica_OutputMessage
    }, // messages
    {// contracts
        {   // BasicHttpBinding_IGraphs4Social_Service
            6,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGraphs4Social_Service.operations,
        },    // end of BasicHttpBinding_IGraphs4Social_Service
    }, // contracts
    { // policies
        {  // template description for BasicHttpBinding_IGraphs4Social_Service
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGraphs4Social_Service.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _tempuri_org_wsdl

HRESULT BasicHttpBinding_IGraphs4Social_Service_CreateServiceProxy(
    __in_opt WS_HTTP_BINDING_TEMPLATE* templateValue,
    __in_ecount_opt(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    __in const ULONG proxyPropertyCount,
    __deref_out_opt WS_SERVICE_PROXY** _serviceProxy,
    __in_opt WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IGraphs4Social_Service,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IGraphs4Social_Service),
        _serviceProxy,
        error);
}

HRESULT BasicHttpBinding_IGraphs4Social_Service_CreateServiceEndpoint(
    __in_opt WS_HTTP_BINDING_TEMPLATE* templateValue,
    __in_opt CONST WS_STRING* address,
    __in_opt struct BasicHttpBinding_IGraphs4Social_ServiceFunctionTable* functionTable,
    __in_opt WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    __in_ecount_opt(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    __in const ULONG endpointPropertyCount,
    __in WS_HEAP* heap,
    __deref_out_opt WS_SERVICE_ENDPOINT** serviceEndpoint,
    __in_opt WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &tempuri_org_wsdl.contracts.BasicHttpBinding_IGraphs4Social_Service;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IGraphs4Social_Service,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IGraphs4Social_Service),
        serviceEndpoint,
        error);
}
