
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct _DoWork;
//     struct _DoWorkResponse;
//     struct _Add;
//     struct _AddResponse;
//     struct _getPessoa;
//     struct _getPessoaResponse;
//     struct _getMusica;
//     struct _getMusicaResponse;
//     struct _getMusicas;
//     struct _getMusicasResponse;
//     struct _findIdMusica;
//     struct _findIdMusicaResponse;

// The following header files must be included in this order before this one

// #include <WebServices.h>
// #include "schema.xsd.h"

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

typedef struct _DoWork _DoWork;

typedef struct _DoWorkResponse _DoWorkResponse;

// typeDescription: n/a
typedef struct _Add 
{
    int x;
    int y;
} _Add;

// typeDescription: n/a
typedef struct _AddResponse 
{
    int AddResult;
} _AddResponse;

// typeDescription: n/a
typedef struct _getPessoa 
{
    int id;
} _getPessoa;

// typeDescription: n/a
typedef struct _getPessoaResponse 
{
    struct Pessoa* getPessoaResult; // optional
} _getPessoaResponse;

// typeDescription: n/a
typedef struct _getMusica 
{
    int id;
} _getMusica;

// typeDescription: n/a
typedef struct _getMusicaResponse 
{
    struct Musica* getMusicaResult; // optional
} _getMusicaResponse;

typedef struct _getMusicas _getMusicas;

// typeDescription: n/a
typedef struct _getMusicasResponse 
{
    unsigned int getMusicasResultCount;
    __field_ecount_opt(getMusicasResultCount)struct Musica** getMusicasResult; // optional
} _getMusicasResponse;

// typeDescription: n/a
typedef struct _findIdMusica 
{
    struct Musica* musica; // optional
} _findIdMusica;

// typeDescription: n/a
typedef struct _findIdMusicaResponse 
{
    int findIdMusicaResult;
} _findIdMusicaResponse;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _tempuri_org_xsd
{
    struct // globalElements
    {
        // xml element: DoWork ("http://tempuri.org/")
        // c type: _DoWork
        // elementDescription: tempuri_org_xsd.globalElements.DoWork
        WS_ELEMENT_DESCRIPTION DoWork;
        
        // xml element: DoWorkResponse ("http://tempuri.org/")
        // c type: _DoWorkResponse
        // elementDescription: tempuri_org_xsd.globalElements.DoWorkResponse
        WS_ELEMENT_DESCRIPTION DoWorkResponse;
        
        // xml element: Add ("http://tempuri.org/")
        // c type: _Add
        // elementDescription: tempuri_org_xsd.globalElements.Add
        WS_ELEMENT_DESCRIPTION Add;
        
        // xml element: AddResponse ("http://tempuri.org/")
        // c type: _AddResponse
        // elementDescription: tempuri_org_xsd.globalElements.AddResponse
        WS_ELEMENT_DESCRIPTION AddResponse;
        
        // xml element: getPessoa ("http://tempuri.org/")
        // c type: _getPessoa
        // elementDescription: tempuri_org_xsd.globalElements.getPessoa
        WS_ELEMENT_DESCRIPTION getPessoa;
        
        // xml element: getPessoaResponse ("http://tempuri.org/")
        // c type: _getPessoaResponse
        // elementDescription: tempuri_org_xsd.globalElements.getPessoaResponse
        WS_ELEMENT_DESCRIPTION getPessoaResponse;
        
        // xml element: getMusica ("http://tempuri.org/")
        // c type: _getMusica
        // elementDescription: tempuri_org_xsd.globalElements.getMusica
        WS_ELEMENT_DESCRIPTION getMusica;
        
        // xml element: getMusicaResponse ("http://tempuri.org/")
        // c type: _getMusicaResponse
        // elementDescription: tempuri_org_xsd.globalElements.getMusicaResponse
        WS_ELEMENT_DESCRIPTION getMusicaResponse;
        
        // xml element: getMusicas ("http://tempuri.org/")
        // c type: _getMusicas
        // elementDescription: tempuri_org_xsd.globalElements.getMusicas
        WS_ELEMENT_DESCRIPTION getMusicas;
        
        // xml element: getMusicasResponse ("http://tempuri.org/")
        // c type: _getMusicasResponse
        // elementDescription: tempuri_org_xsd.globalElements.getMusicasResponse
        WS_ELEMENT_DESCRIPTION getMusicasResponse;
        
        // xml element: findIdMusica ("http://tempuri.org/")
        // c type: _findIdMusica
        // elementDescription: tempuri_org_xsd.globalElements.findIdMusica
        WS_ELEMENT_DESCRIPTION findIdMusica;
        
        // xml element: findIdMusicaResponse ("http://tempuri.org/")
        // c type: _findIdMusicaResponse
        // elementDescription: tempuri_org_xsd.globalElements.findIdMusicaResponse
        WS_ELEMENT_DESCRIPTION findIdMusicaResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION DoWork;
        WS_STRUCT_DESCRIPTION DoWorkResponse;
        WS_STRUCT_DESCRIPTION Add;
        WS_STRUCT_DESCRIPTION AddResponse;
        WS_STRUCT_DESCRIPTION getPessoa;
        WS_STRUCT_DESCRIPTION getPessoaResponse;
        WS_STRUCT_DESCRIPTION getMusica;
        WS_STRUCT_DESCRIPTION getMusicaResponse;
        WS_STRUCT_DESCRIPTION getMusicas;
        WS_STRUCT_DESCRIPTION getMusicasResponse;
        WS_STRUCT_DESCRIPTION findIdMusica;
        WS_STRUCT_DESCRIPTION findIdMusicaResponse;
    } externallyReferencedTypes;
} _tempuri_org_xsd;

extern const _tempuri_org_xsd tempuri_org_xsd;

#ifdef __cplusplus
}
#endif

