
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schema.xsd.h"
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct // _Add
        {
            WS_FIELD_DESCRIPTION x;
            WS_FIELD_DESCRIPTION y;
            WS_FIELD_DESCRIPTION* _AddFields [2]; 
        } _Adddescs; // end of _Add
        struct // _AddResponse
        {
            WS_FIELD_DESCRIPTION AddResult;
            WS_FIELD_DESCRIPTION* _AddResponseFields [1]; 
        } _AddResponsedescs; // end of _AddResponse
        struct // _getPessoa
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION* _getPessoaFields [1]; 
        } _getPessoadescs; // end of _getPessoa
        struct // _getPessoaResponse
        {
            WS_FIELD_DESCRIPTION getPessoaResult;
            WS_FIELD_DESCRIPTION* _getPessoaResponseFields [1]; 
        } _getPessoaResponsedescs; // end of _getPessoaResponse
        struct // _getMusica
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION* _getMusicaFields [1]; 
        } _getMusicadescs; // end of _getMusica
        struct // _getMusicaResponse
        {
            WS_FIELD_DESCRIPTION getMusicaResult;
            WS_FIELD_DESCRIPTION* _getMusicaResponseFields [1]; 
        } _getMusicaResponsedescs; // end of _getMusicaResponse
        struct // _getMusicasResponse
        {
            WS_FIELD_DESCRIPTION getMusicasResult;
            WS_FIELD_DESCRIPTION* _getMusicasResponseFields [1]; 
        } _getMusicasResponsedescs; // end of _getMusicasResponse
        struct // _findIdMusica
        {
            WS_FIELD_DESCRIPTION musica;
            WS_FIELD_DESCRIPTION* _findIdMusicaFields [1]; 
        } _findIdMusicadescs; // end of _findIdMusica
        struct // _findIdMusicaResponse
        {
            WS_FIELD_DESCRIPTION findIdMusicaResult;
            WS_FIELD_DESCRIPTION* _findIdMusicaResponseFields [1]; 
        } _findIdMusicaResponsedescs; // end of _findIdMusicaResponse
    } globalElements;  // end of global elements
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING _DoWorkTypeName;  // DoWork
            WS_XML_STRING _DoWorkTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _DoWorkResponseTypeName;  // DoWorkResponse
            WS_XML_STRING _AddTypeName;  // Add
            WS_XML_STRING _AddxLocalName;  // x
            WS_XML_STRING _AddyLocalName;  // y
            WS_XML_STRING _AddResponseTypeName;  // AddResponse
            WS_XML_STRING _AddResponseAddResultLocalName;  // AddResult
            WS_XML_STRING _getPessoaTypeName;  // getPessoa
            WS_XML_STRING _getPessoaidLocalName;  // id
            WS_XML_STRING _getPessoaResponseTypeName;  // getPessoaResponse
            WS_XML_STRING _getPessoaResponsegetPessoaResultLocalName;  // getPessoaResult
            WS_XML_STRING _getMusicaTypeName;  // getMusica
            WS_XML_STRING _getMusicaResponseTypeName;  // getMusicaResponse
            WS_XML_STRING _getMusicaResponsegetMusicaResultLocalName;  // getMusicaResult
            WS_XML_STRING _getMusicasTypeName;  // getMusicas
            WS_XML_STRING _getMusicasResponseTypeName;  // getMusicasResponse
            WS_XML_STRING _getMusicasResponsegetMusicasResultLocalName;  // Musica
            WS_XML_STRING _getMusicasResponsegetMusicasResultNamespace;  // http://schemas.datacontract.org/2004/07/
            WS_XML_STRING _getMusicasResponsegetMusicasResultWrapperName;  // getMusicasResult
            WS_XML_STRING _findIdMusicaTypeName;  // findIdMusica
            WS_XML_STRING _findIdMusicamusicaLocalName;  // musica
            WS_XML_STRING _findIdMusicaResponseTypeName;  // findIdMusicaResponse
            WS_XML_STRING _findIdMusicaResponsefindIdMusicaResultLocalName;  // findIdMusicaResult
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {   // _Add
            { // field description for x
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddxLocalName, // x
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, x),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for x
            { // field description for y
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddyLocalName, // y
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, y),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for y
            {    // fields description for _Add
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.x,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.y,
            },
        },    // _Add
        {   // _AddResponse
            { // field description for AddResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseAddResultLocalName, // AddResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_AddResponse, AddResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for AddResult
            {    // fields description for _AddResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs.AddResult,
            },
        },    // _AddResponse
        {   // _getPessoa
            { // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getPessoaidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getPessoa, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            {    // fields description for _getPessoa
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getPessoadescs.id,
            },
        },    // _getPessoa
        {   // _getPessoaResponse
            { // field description for getPessoaResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getPessoaResponsegetPessoaResultLocalName, // getPessoaResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Pessoa,
            WsOffsetOf(_getPessoaResponse, getPessoaResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for getPessoaResult
            {    // fields description for _getPessoaResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getPessoaResponsedescs.getPessoaResult,
            },
        },    // _getPessoaResponse
        {   // _getMusica
            { // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getPessoaidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getMusica, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            {    // fields description for _getMusica
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getMusicadescs.id,
            },
        },    // _getMusica
        {   // _getMusicaResponse
            { // field description for getMusicaResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicaResponsegetMusicaResultLocalName, // getMusicaResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Musica,
            WsOffsetOf(_getMusicaResponse, getMusicaResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for getMusicaResult
            {    // fields description for _getMusicaResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getMusicaResponsedescs.getMusicaResult,
            },
        },    // _getMusicaResponse
        {   // _getMusicasResponse
            { // field description for getMusicasResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicasResponsegetMusicasResultWrapperName, // getMusicasResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Musica,
            WsOffsetOf(_getMusicasResponse, getMusicasResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_getMusicasResponse, getMusicasResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicasResponsegetMusicasResultLocalName, // Musica
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicasResponsegetMusicasResultNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for getMusicasResult
            {    // fields description for _getMusicasResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getMusicasResponsedescs.getMusicasResult,
            },
        },    // _getMusicasResponse
        {   // _findIdMusica
            { // field description for musica
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._findIdMusicamusicaLocalName, // musica
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Musica,
            WsOffsetOf(_findIdMusica, musica),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for musica
            {    // fields description for _findIdMusica
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._findIdMusicadescs.musica,
            },
        },    // _findIdMusica
        {   // _findIdMusicaResponse
            { // field description for findIdMusicaResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._findIdMusicaResponsefindIdMusicaResultLocalName, // findIdMusicaResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_findIdMusicaResponse, findIdMusicaResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for findIdMusicaResult
            {    // fields description for _findIdMusicaResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._findIdMusicaResponsedescs.findIdMusicaResult,
            },
        },    // _findIdMusicaResponse
    }, // end of global elements
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("DoWork",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("DoWorkResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("Add",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("x",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("y",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("AddResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("AddResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("getPessoa",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("id",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("getPessoaResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("getPessoaResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("getMusica",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("getMusicaResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("getMusicaResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("getMusicas",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("getMusicasResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("Musica",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("getMusicasResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("findIdMusica",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("musica",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("findIdMusicaResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("findIdMusicaResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 23),
        },  // end of xmlStrings
        
        {   // tempuri_org_xsddictionary
        // 21ac393a-40e7-4455-b675-1929f9d533e6 
        { 0x21ac393a, 0x40e7, 0x4455, { 0xb6, 0x75, 0x19,0x29, 0xf9, 0xd5, 0x33, 0xe6 } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        24,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {// globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeName, // DoWork
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DoWork,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkResponseTypeName, // DoWorkResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DoWorkResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.Add,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.AddResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getPessoaTypeName, // getPessoa
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getPessoa,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getPessoaResponseTypeName, // getPessoaResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getPessoaResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicaTypeName, // getMusica
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getMusica,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicaResponseTypeName, // getMusicaResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getMusicaResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicasTypeName, // getMusicas
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getMusicas,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicasResponseTypeName, // getMusicasResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getMusicasResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._findIdMusicaTypeName, // findIdMusica
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.findIdMusica,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._findIdMusicaResponseTypeName, // findIdMusicaResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.findIdMusicaResponse,
        },
    }, // globalElements
    {  // begin of externallyReferencedTypes
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeName, // DoWork
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DoWork
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkResponseTypeName, // DoWorkResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DoWorkResponse
        {
        sizeof(_Add),
        __alignof(_Add),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _Add
        {
        sizeof(_AddResponse),
        __alignof(_AddResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _AddResponse
        {
        sizeof(_getPessoa),
        __alignof(_getPessoa),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getPessoadescs._getPessoaFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getPessoadescs._getPessoaFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getPessoaTypeName, // getPessoa
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getPessoa
        {
        sizeof(_getPessoaResponse),
        __alignof(_getPessoaResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getPessoaResponsedescs._getPessoaResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getPessoaResponsedescs._getPessoaResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getPessoaResponseTypeName, // getPessoaResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getPessoaResponse
        {
        sizeof(_getMusica),
        __alignof(_getMusica),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getMusicadescs._getMusicaFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getMusicadescs._getMusicaFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicaTypeName, // getMusica
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getMusica
        {
        sizeof(_getMusicaResponse),
        __alignof(_getMusicaResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getMusicaResponsedescs._getMusicaResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getMusicaResponsedescs._getMusicaResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicaResponseTypeName, // getMusicaResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getMusicaResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicasTypeName, // getMusicas
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getMusicas
        {
        sizeof(_getMusicasResponse),
        __alignof(_getMusicasResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getMusicasResponsedescs._getMusicasResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getMusicasResponsedescs._getMusicasResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMusicasResponseTypeName, // getMusicasResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getMusicasResponse
        {
        sizeof(_findIdMusica),
        __alignof(_findIdMusica),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._findIdMusicadescs._findIdMusicaFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._findIdMusicadescs._findIdMusicaFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._findIdMusicaTypeName, // findIdMusica
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _findIdMusica
        {
        sizeof(_findIdMusicaResponse),
        __alignof(_findIdMusicaResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._findIdMusicaResponsedescs._findIdMusicaResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._findIdMusicaResponsedescs._findIdMusicaResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._findIdMusicaResponseTypeName, // findIdMusicaResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _findIdMusicaResponse
    }, // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
